### ISSUE TITLE
Three Different Glitches

### ISSUE THREAD

**Issue by eglbogle** [Steffion/BlockHunt#324]
While playing Block Hunt, there are 3 different glitches I found that are game-breaking:

1. The Block Chooser doesn't work even with all given permissions. When you try to select the block from the inventory that it pulls up, it takes the block out like it's a chest.

2. Hiders can't kill or damage in any way harm the Seekers because they're in godmode.

3. Hiders are invisible when they begin to hide. As long as they're moving, they will remain invisible.

Are there any fixes for these glitches?

**Comment by Sammayboy123** [comment]
I am experiencing the same thing because I downloaded it from the same source, the hiders are invisible when they run, and not possible to kill, nor are the seekers because they are invincible

**Comment by tyiscool97** [comment]
We just tried this same setup today and we had the same problems. Hiders vanish while running and seekers appear to be invincible. Hope there is a fix.

**Comment by eglbogle** [comment]
Yeah, we all downloaded it from the same place, and we all have the same version of ProtocolLib and Lib's Disguises.

**Comment by NoHoPeLess** [comment]
is there any help for this? We love this plugin so much! We have the exact same issues...

**Comment by addstar** [comment]
Feel free to try our my unofficial builds (it is a fork, as mentioned in Issue #320).
The latest build is live on my own server and we don't have these issues (except for the seeker invincibility - we specifically wanted that). Works perfectly fine in 1.7 or 1.8 (we have used the same version in both).

NOTE: I have no association with @Steffion and they get all credit for creating the plugin initially, but since there has been no official activity for 12+ months, I think it's safe to say the official plugin is abandoned... so I updated it and added other features too :grin: 

Unofficial builds: http://jenkins.addstar.com.au/job/BlockHunt/
GitHub: https://github.com/addstar/BlockHunt/

**Comment by eglbogle** [comment]
Is the seeker invincibility configurable? That'd be nice

**Comment by eglbogle** [comment]
The latest release doesn't work. In addition to the other 3 glitches, a 4th has been added. Now, hiders don't die. They make the damage sounds when hit, but don't actually take any damage.

**Comment by addstar** [comment]
@eglbogle thats very strange.. it's likely to be something with your specific setup. Rather than hijack this thread, can make an issue on my project and provide more info (eg. server build/version, pastebin config, etc)?

**Comment by xion87** [comment]
same thing hiders can't die... after your latest update #22  i think... I am using spigot 1.8, my config 
config.yml http://pastebin.com/87g2aJSZ
arenas.yml http://pastebin.com/ispD7Hwj
I was thing the feature of invicible seekers was added....as your feature....

**Comment by NoHoPeLess** [comment]
We use : 
-Spigot-1649
-ProtocolLib v3.6.0-SNAPSHOT
-LibsDisguises v8.2.6
-BlockHunt v0.2.1-b26

Serverlog: http://pastebin.com/4im2xmnn

Config: http://pastebin.com/nE7Uz0tE

Arenas: http://pastebin.com/9BczQTCv

Hope this helps to solve the bugs

**Comment by addstar** [comment]
FYI - Anyone using [my custom BlockHunt builds](http://jenkins.addstar.com.au/job/BlockHunt/) should be creating issues on [my github project](https://github.com/addstar/BlockHunt) not on here.. This project is only for the (now abandoned) official BlockHunt, let's not hijack this one.

**Comment by NoHoPeLess** [comment]
I make an issue on: https://github.com/addstar/BlockHunt/issues/5

**Comment by RandomPanda30** [comment]
@addstar BlockHunt is not abandoned

**Comment by addstar** [comment]
@RandomPanda30 sorry about that, I did not intend to offend. I just assumed because it had been 12+ months since any activity. Our players love this game but with 1.7.9+ the plugin was unusable due to UUID lookup issues. So I forked the project and fixed a bunch of stuff to make it work :grin: 

Never intended to become the de-facto version, it was only made to be used on our own server but as with all our projects, they're openly shared and people started to find it.

Great to hear you guys are planning to work on it again! Looking forward to seeing what you have planned :+1:

**Comment by RandomPanda30** [comment]
@addstar Ayyy don't worry. I may have sounded a bit arrogant there and I didn't mean to come across as that type of person.Thank you for making the project work whilst Steffion and I are currently focusing on other things.

Alright, so the whole thing needs recoding. It'll be hard but the whole thing needs a full recode. Steffion built BlockHunt on an engine that now has become pretty much dead and yeahhh it needs coding from scratch which shouldn't be a problem.

However, we'll have issues with LibsDisguise since the main dev for that has gone and yeahhh, it's going to be hard. We may end up implementing our own disguise system into BlockHunt, who knows?

Thank you for keeping the project alive. Make sure you keep watching here for the new version which should be out soon ;3

**Comment by eglbogle** [comment]
Also, I think I've found the problem with hider invisibility. It doesn't appear to be an issue with Block Hunt, but I have confirmed it's an issue with Lib's Disguises. When you disguise using Lib's Disguises, it  turns the user invisible randomly. I'll post something on there.

**Comment by RandomPanda30** [comment]
@eglbogle Hmmmm I think LibsDisguise is not going to be updated anymore which is incredibly sad ;-; I hope it gets updated and done soon.

**Comment by addstar** [comment]
@RandomPanda30 There are several forks of LibsDisguises so hopefully someone continues to update and maintain it. LibsDisguises is working fairly well for me at the moment (with the exception of a few issues). But we might end up trying one of the forks and see if they are better. We can only hope someone takes over :smiley:

**Comment by RandomPanda30** [comment]
@addstar I think this will be the best idea for BlockHunt. We'll have to see what happens anyway. Let us know if you find any updates on the LibsDisguise plugin. We did use DisguiseCraft at one point but that's way too buggy now and it doesn't really work as fluently as LibsDisguise.

**Comment by coolnickname** [comment]
I don't think the hiders are invisable, i think you got the seme problem as me: the blocks are not shown at the right place, the shown like 30 blocks from the place where the hider is.

**Comment by xion87** [comment]
Lib's disguises is still mantained by another author :) so please keep update it!

**Comment by Steffion** [comment]
For those who are concerned, I might be recoding the plugin soon for better functionality and less lag (hopefully).

Check out the 'recode' branch (not that much there yet) https://github.com/Steffion/BlockHunt/tree/recode
Please keep in mind the read-me:
>BlockHunt
Welcome to the recode branch of the BlockHunt repository!

>You can follow my proggress of recoding the BlockHunt plugin here. I am not sure if I will finish the plugin. More information will follow.

**Comment by elliswin** [comment]
Hi all,
I'm a little confused about which version I should be using now, I had a problem of people not getting their tokens, so I installed addstar's version which fixed the token issue, but now hidden players are unable to strike the seeker at all, and also I am getting the odd player being invisible, so to recap were using the following versions on the server:

Blockhunt 0.2.1-b26 from addstar's link.
ProtocolLib 3.6.3 Snapshot-B114
LibDisguises 8.3.2
and Spiggot with version 1.8.3 of Minecraft.

Can someone advise us of the best configuration to get this to work smoothly.

Thanks in advance
EllisWin
SafeCraft.co.uk

**Comment by Steffion** [comment]
There might be some bugs in the plugin, I would advice you to keep using addstar's version for now.

Make sure other plugins are not interfering with it.




I can’t help much more since the plugin is just really broken and needs to be recoded.




Kind regards,




Steffion


On Tuesday, Apr 14, 2015 at 4:44 pm, EllisWIn <notifications@github.com>, wrote:

Hi all,

I'm a little confused about which version I should be using now, I had a problem of people not getting their tokens, so I installed addstar's version which fixed the token issue, but now hidden players are unable to strike the seeker at all, and also I am getting the odd player being invisible, so to recap were using the following versions on the server:


Blockhunt 0.2.1-b26 from addstar's link.

ProtocolLib 3.6.3 Snapshot-B114

LibDisguises 8.3.2

and Spiggot with version 1.8.3 of Minecraft.


Can someone advise us of the best configuration to get this to work smoothly.


Thanks in advance

EllisWin

SafeCraft.co.uk

**Comment by Steffion** [comment]
I am going to close this for now. If you still have any problems, please create a new issue.
